# This is a basic workflow to help you get started with Actions

name: Docs

# build the documentation whenever there's a new version tag
# or manually
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # install Poetry, project dependencies, and build docs
      - run: |
          export POETRY_HOME=~/poetry.env
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry==1.6.1
          $POETRY_HOME/bin/poetry --version
          $POETRY_HOME/bin/poetry install
          $POETRY_HOME/bin/poetry run python tools/make-docs.py

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
